export const DATA_INFO_REQUEST = "DATA_INFO_REQUEST";
export const DATA_INFO_SUCCESS = "DATA_INFO_SUCCESS";
export const DATA_INFO_FAIL = "DATA_INFO_FAIL";

export const DATA_CREATE_REQUEST = "DATA_CREATE_REQUEST";
export const DATA_CREATE_SUCCESS = "DATA_CREATE_SUCCESS";
export const DATA_CREATE_FAIL = "DATA_CREATE_FAIL";